### ISSUE TITLE
Question: Regarding Calendar header.

### ISSUE THREAD

**Issue by h-elbeheiry** [shohe/InfiniteCalendar#1]
Where I can find the code for this part ? I wanna change how the active Day UI looks like.

<img width="407" alt="Screen Shot 2022-05-26 at 9 59 45 AM" src="https://user-images.githubusercontent.com/14643031/170503526-305da175-24b9-4145-9be0-f0c79b82300c.png">

Thanks for the awesome Repo, great job.

**Comment by shohe** [comment]
Basically, you can create custom UI component, with 3 custom classes like **Sample custom component (Timeline)** in **4. Custom UI components** Section on README.

I tried it but there was some access error problem for component item property and bugs.
So I’m trying to fix it, sorry about that. After solve this issue, I'll update Demo app too.

**Comment by shohe** [comment]
@h-elbeheiry 
I fixed some bugs for customize components.  I wrote how to customize UI on README too, please look at it.
Or please check my sample code here on bellow.

https://github.com/shohe/InfiniteCalendar/blob/main/Demo/CustomUI/CustomDateHeader.swift

**Comment by h-elbeheiry** [comment]
> @h-elbeheiry I fixed some bugs for customize components. I wrote how to customize UI on README too, please look at it. Or please check my sample code here on bellow.
> 
> https://github.com/shohe/InfiniteCalendar/blob/main/Demo/CustomUI/CustomDateHeader.swift

Thank you so much for the demo code its very helpful and thanks for responding 🙂
