### ISSUE TITLE
Question: 12 hours format ?

### ISSUE THREAD

**Issue by h-elbeheiry** [shohe/InfiniteCalendar#2]
How can I set the Calendar to show 12 hours format with AM and PM rather than 24 hrs format ?

**Comment by shohe** [comment]
You need to create custom class of `ICTimeHeader` and `ICTimeHeaderView` like CustomDateHeader on Demo.
You will be able to get ICTimeHeaderItem which has date property.

Here is default components code, it'll be helpful when you create custom class.
👇
https://github.com/shohe/InfiniteCalendar/blob/main/Sources/Component/DefaultComponents/ICTimeHeader.swift#L27-L29

**Comment by h-elbeheiry** [comment]
> You need to create custom class of `ICTimeHeader` and `ICTimeHeaderView` like CustomDateHeader on Demo. You will be able to get ICTimeHeaderItem which has date property.
> 
> Here is default components code, it'll be helpful when you create custom class. 👇 https://github.com/shohe/InfiniteCalendar/blob/main/Sources/Component/DefaultComponents/ICTimeHeader.swift#L27-L29

Thank you
