### ISSUE TITLE
dateheaderview and timeline view is not visible when running the Demo target

### ISSUE THREAD

**Issue by jatinmishra** [shohe/InfiniteCalendar#3]
Hi,

When we try to run the Demo app target in the project the headerview and timeline view is not visible.
<img width="427" alt="image" src="https://user-images.githubusercontent.com/25502209/188656082-fea75dbc-a7b7-41d4-bd14-c544460cef46.png">

The app runs fine when we add the InfiniteCalendar via SPM in a fresh project.

Thanks.

**Comment by shohe** [comment]
@jatinmishra
I fixed this bug. Please check it again.

**Comment by jatinmishra** [comment]
Thanks @shohe 
It is working fine now.
I am closing this issue.
