### ISSUE TITLE
Scrolling through days and changing views, then scrolling more and then tapping current day icon causes crash.

### ISSUE THREAD

**Issue by quickjeff** [shohe/InfiniteCalendar#4]
@shohe 
If you start  with the daily view, then scroll a few days forward, then scroll back and then change to weekly view, then scroll more, up and down, then change view to 3 days, then day, then back to weekly and tap the current day icon, it will cause out of index range crash.
`// MARK: - ICViewFlowLayoutDelegate
    public func collectionView(_ collectionView: UICollectionView, layout: ICViewFlowLayout<Settings>, dayForSection section: Int) -> Date {
        return getDateForSection(section)
    }
    
    public func collectionView(_ collectionView: UICollectionView, layout: ICViewFlowLayout<Settings>, startTimeForItemAtIndexPath indexPath: IndexPath) -> Date {
        let date = layout.date(forDateHeaderAt: indexPath)
        
        if let events = events[date] {
            return events[indexPath.item].intraStartDate
        } else {
            print("Connot get events at \(date)")
            return Date()
        }
    }`

<img width="1094" alt="Screenshot 2023-02-22 at 9 32 28 PM" src="https://user-images.githubusercontent.com/8950949/220815712-3f299b0f-64ef-4331-be08-200daddcde2e.png">

**Comment by shohe** [comment]
@quickjeff 
Thank you for notify me about the bug.

I fixed this line. Also fixed for endTimeForItem code.

https://github.com/shohe/InfiniteCalendar/blob/39a5b1256c442adde5b4ff5bf952a7b33470b0ac/Sources/View/ICBaseView.swift#LL470C15-L470C15

**Comment by quickjeff** [comment]
Amazing, I'll give it a try now. Appreciate the effort!
